### ISSUE TITLE
git private key leaked

### ISSUE THREAD

**Issue by look4regev** [vsoch/dockerfiles#8]
Your id_rsa should not be visible to the world. Rotate it (if you haven't already did) and remove it.
https://github.com/vsoch/dockerfiles/blob/e8794a14ec86d8c03b3a00d1b9a659147f992e68/data/c/courtyard/store/Dockerfile

**Comment by vsoch** [comment]
Thanks @look4regev I removed the file - these aren't my Dockerfiles, they were scraped from Docker Hub back in 2017. I definitely haven't done anything in the way of curation or checking for these aspects.

**Comment by vsoch** [comment]
I would consider contacting the original author, [courtyard/store](https://hub.docker.com/r/courtyard/store)
